---
title: "DASC 1104 Project Proposal"
author: "Gerardo Moreno"
date: 12-3-20
output: pdf_document
---

<link href="/rmarkdown-libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="/rmarkdown-libs/anchor-sections/anchor-sections.js"></script>


<p>My blog is available at <a href="https://dasc-1104-finalproject-blog.netlify.app" class="uri">https://dasc-1104-finalproject-blog.netlify.app</a></p>
<pre class="r"><code>library(here)</code></pre>
<pre><code>## here() starts at /home/gdmoreno/finalproject</code></pre>
<pre class="r"><code>library(ggplot2)
library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ tibble  2.1.3     ✓ dplyr   0.8.3
## ✓ tidyr   1.0.0     ✓ stringr 1.4.0
## ✓ readr   1.3.1     ✓ forcats 0.4.0
## ✓ purrr   0.3.3</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>library(readxl)
library(tinytex)
library(fivethirtyeight)
knitr::opts_chunk$set(echo = FALSE, tidy = TRUE)
epl1 &lt;- read.csv(file = here::here(&quot;epl_data&quot;, &quot;epl2020.csv&quot;))
epl2 &lt;- read.csv(file = here::here(&quot;epl_data&quot;, &quot;EPL_19_20_GW_Timeseries.csv&quot;))
epl3 &lt;- read.csv(file = here::here(&quot;epl_data&quot;, &quot;epl_players_stats.csv&quot;))
epl4 &lt;- read.csv(file = here::here(&quot;epl_data&quot;, &quot;players_1920_fin.csv&quot;))
glimpse(epl1)</code></pre>
<pre><code>## Observations: 576
## Variables: 45
## $ X            &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1…
## $ h_a          &lt;fct&gt; h, a, a, h, h, a, h, h, a, a, a, h, a, h, a, h, h, a, a,…
## $ xG           &lt;dbl&gt; 2.234560, 0.842407, 3.183770, 1.200300, 1.340990, 0.8555…
## $ xGA          &lt;dbl&gt; 0.842407, 2.234560, 1.200300, 3.183770, 1.598640, 0.6700…
## $ npxG         &lt;dbl&gt; 2.234560, 0.842407, 2.422640, 1.200300, 1.340990, 0.8555…
## $ npxGA        &lt;dbl&gt; 0.842407, 2.234560, 1.200300, 2.422640, 1.598640, 0.6700…
## $ deep         &lt;int&gt; 11, 5, 9, 1, 4, 5, 0, 5, 5, 6, 9, 7, 2, 15, 10, 7, 1, 3,…
## $ deep_allowed &lt;int&gt; 5, 11, 1, 9, 6, 7, 9, 5, 5, 4, 0, 5, 15, 2, 1, 3, 10, 7,…
## $ scored       &lt;int&gt; 4, 1, 5, 0, 1, 3, 3, 0, 0, 1, 0, 0, 1, 3, 1, 0, 0, 0, 0,…
## $ missed       &lt;int&gt; 1, 4, 0, 5, 1, 0, 0, 0, 0, 1, 3, 3, 3, 1, 0, 0, 1, 0, 4,…
## $ xpts         &lt;dbl&gt; 2.3863, 0.4405, 2.6312, 0.2522, 1.0172, 1.5458, 1.1422, …
## $ result       &lt;fct&gt; w, l, w, l, d, w, w, d, d, d, l, l, l, w, w, d, l, d, l,…
## $ date         &lt;fct&gt; 2019-08-09 20:00:00, 2019-08-09 20:00:00, 2019-08-10 12:…
## $ wins         &lt;int&gt; 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,…
## $ draws        &lt;int&gt; 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,…
## $ loses        &lt;int&gt; 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,…
## $ pts          &lt;int&gt; 3, 0, 3, 0, 1, 3, 3, 1, 1, 1, 0, 0, 0, 3, 3, 1, 0, 1, 0,…
## $ npxGD        &lt;dbl&gt; 1.392153, -1.392153, 1.222340, -1.222340, -0.257650, 0.1…
## $ teamId       &lt;fct&gt; Liverpool, Norwich, Man City, West Ham, Bournemouth, Bri…
## $ ppda_cal     &lt;dbl&gt; 5.942857, 21.454545, 6.935484, 16.400000, 13.600000, 11.…
## $ allowed_ppda &lt;dbl&gt; 21.454545, 5.942857, 16.400000, 6.935484, 9.133333, 9.78…
## $ matchtime    &lt;int&gt; 20, 20, 12, 12, 15, 15, 15, 15, 15, 15, 15, 15, 17, 17, …
## $ tot_points   &lt;int&gt; 3, 0, 3, 0, 1, 3, 3, 1, 1, 1, 0, 0, 0, 3, 3, 1, 0, 1, 0,…
## $ round        &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
## $ tot_goal     &lt;int&gt; 4, 1, 5, 0, 1, 3, 3, 0, 0, 1, 0, 0, 1, 3, 1, 0, 0, 0, 0,…
## $ tot_con      &lt;int&gt; 1, 4, 0, 5, 1, 0, 0, 0, 0, 1, 3, 3, 3, 1, 0, 0, 1, 0, 4,…
## $ Referee.x    &lt;fct&gt; M Oliver, M Oliver, M Dean, M Dean, K Friend, C Pawson, …
## $ HS.x         &lt;int&gt; 15, 15, 5, 5, 13, 11, 10, 6, 6, 13, 10, 11, 31, 31, 9, 1…
## $ HST.x        &lt;int&gt; 7, 7, 3, 3, 3, 3, 4, 2, 2, 3, 4, 3, 7, 7, 2, 1, 2, 1, 5,…
## $ HF.x         &lt;int&gt; 9, 9, 6, 6, 10, 15, 6, 16, 16, 10, 6, 15, 13, 13, 12, 3,…
## $ HC.x         &lt;int&gt; 11, 11, 1, 1, 3, 5, 2, 6, 6, 3, 2, 5, 14, 14, 5, 12, 5, …
## $ HY.x         &lt;int&gt; 0, 0, 2, 2, 2, 0, 0, 2, 2, 2, 0, 0, 1, 1, 1, 0, 1, 0, 3,…
## $ HR.x         &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ AS.x         &lt;int&gt; 12, 12, 14, 14, 8, 5, 11, 10, 10, 8, 11, 5, 7, 7, 8, 8, …
## $ AST.x        &lt;int&gt; 5, 5, 9, 9, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 2, 2, 2, 2, 7,…
## $ AF.x         &lt;int&gt; 9, 9, 13, 13, 19, 11, 12, 14, 14, 19, 12, 11, 9, 9, 7, 1…
## $ AC.x         &lt;int&gt; 2, 2, 1, 1, 4, 2, 7, 2, 2, 4, 7, 2, 0, 0, 3, 3, 3, 3, 5,…
## $ AY.x         &lt;int&gt; 2, 2, 2, 2, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 3, 2, 3, 2, 4,…
## $ AR.x         &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ B365H.x      &lt;dbl&gt; 1.14, 1.14, 12.00, 12.00, 1.95, 1.90, 2.62, 3.00, 3.00, …
## $ B365D.x      &lt;dbl&gt; 10.00, 10.00, 6.50, 6.50, 3.60, 3.40, 3.20, 3.25, 3.25, …
## $ B365A.x      &lt;dbl&gt; 19.00, 19.00, 1.22, 1.22, 3.60, 4.00, 2.75, 2.37, 2.37, …
## $ HtrgPerc     &lt;dbl&gt; 0.46666667, 0.46666667, 0.60000000, 0.60000000, 0.230769…
## $ AtrgPerc     &lt;dbl&gt; 0.4166667, 0.4166667, 0.6428571, 0.6428571, 0.3750000, 0…
## $ matchDay     &lt;fct&gt; Fri, Fri, Sat, Sat, Sat, Sat, Sat, Sat, Sat, Sat, Sat, S…</code></pre>
<pre><code>## Observations: 1,048,575
## Variables: 77
## $ Teams          &lt;fct&gt;  MCI, MUN, LIV, BHA, BUR, TOT, ARS, BOU, SHU, CRY, EVE…
## $ GW1_Points     &lt;int&gt; 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, …
## $ GW1_Standing   &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,…
## $ GW2_Points     &lt;int&gt; 4, 4, 6, 4, 3, 4, 6, 4, 4, 1, 4, 2, 2, 0, 0, 3, 0, 0, …
## $ GW2_Standing   &lt;int&gt; 3, 4, 1, 5, 10, 6, 2, 7, 8, 14, 9, 12, 13, 18, 17, 11,…
## $ GW3_Points     &lt;int&gt; 7, 4, 9, 4, 4, 4, 6, 4, 4, 4, 4, 5, 3, 3, 3, 3, 3, 3, …
## $ GW3_Standing   &lt;int&gt; 2, 5, 1, 8, 6, 7, 3, 11, 9, 10, 12, 4, 15, 19, 16, 17,…
## $ GW4_Points     &lt;int&gt; 10, 5, 12, 4, 4, 5, 7, 4, 5, 7, 7, 8, 3, 4, 3, 3, 4, 1…
## $ GW4_Standing   &lt;int&gt; 2, 8, 1, 16, 12, 9, 5, 15, 10, 4, 6, 3, 17, 14, 18, 19…
## $ GW5_Points     &lt;int&gt; 10, 8, 15, 5, 5, 8, 8, 7, 5, 7, 7, 8, 3, 4, 4, 6, 7, 2…
## $ GW5_Standing   &lt;int&gt; 2, 4, 1, 16, 14, 3, 7, 9, 15, 12, 11, 5, 19, 18, 17, 1…
## $ GW6_Points     &lt;int&gt; 13, 8, 18, 6, 8, 8, 11, 10, 8, 8, 7, 11, 4, 5, 4, 6, 7…
## $ GW6_Standing   &lt;int&gt; 2, 8, 1, 15, 9, 7, 4, 6, 10, 12, 14, 3, 19, 17, 18, 16…
## $ GW7_Points     &lt;int&gt; 16, 9, 21, 6, 9, 11, 12, 11, 8, 11, 7, 14, 7, 5, 5, 6,…
## $ GW7_Standing   &lt;int&gt; 2, 10, 1, 16, 11, 6, 4, 8, 12, 9, 15, 3, 13, 19, 18, 1…
## $ GW8_Points     &lt;int&gt; 16, 9, 24, 9, 12, 11, 15, 11, 9, 14, 7, 14, 10, 8, 8, …
## $ GW8_Standing   &lt;int&gt; 2, 12, 1, 14, 7, 9, 3, 10, 13, 6, 18, 4, 11, 16, 15, 1…
## $ GW9_Points     &lt;int&gt; 19, 10, 25, 9, 12, 12, 15, 12, 12, 14, 10, 17, 11, 8, …
## $ GW9_Standing   &lt;int&gt; 2, 14, 1, 16, 8, 7, 5, 10, 9, 6, 15, 3, 13, 18, 12, 19…
## $ GW10_Points    &lt;int&gt; 22, 13, 28, 12, 12, 12, 16, 13, 13, 15, 10, 20, 12, 9,…
## $ GW10_Standing  &lt;int&gt; 2, 7, 1, 14, 13, 11, 5, 9, 8, 6, 16, 3, 12, 17, 15, 19…
## $ GW11_Points    &lt;int&gt; 25, 13, 31, 15, 12, 13, 17, 16, 16, 15, 11, 23, 13, 12…
## $ GW11_Standing  &lt;int&gt; 2, 10, 1, 8, 14, 11, 5, 7, 6, 9, 17, 3, 12, 15, 16, 19…
## $ GW12_Points    &lt;int&gt; 25, 16, 34, 15, 15, 14, 17, 16, 17, 15, 14, 26, 16, 15…
## $ GW12_Standing  &lt;int&gt; 4, 7, 1, 11, 10, 14, 6, 9, 5, 12, 15, 2, 8, 13, 17, 20…
## $ GW13_Points    &lt;int&gt; 28, 17, 37, 15, 18, 17, 18, 16, 18, 15, 14, 29, 19, 15…
## $ GW13_Standing  &lt;int&gt; 3, 9, 1, 12, 7, 10, 8, 11, 6, 13, 16, 2, 5, 14, 15, 18…
## $ GW14_Points    &lt;int&gt; 29, 18, 40, 15, 18, 20, 19, 16, 19, 18, 14, 32, 20, 16…
## $ GW14_Standing  &lt;int&gt; 3, 9, 1, 16, 10, 5, 8, 12, 7, 11, 17, 2, 6, 14, 15, 19…
## $ GW15_Points    &lt;int&gt; 32, 21, 43, 18, 18, 20, 19, 16, 19, 21, 14, 35, 23, 19…
## $ GW15_Standings &lt;int&gt; 3, 6, 1, 13, 12, 8, 10, 14, 9, 7, 18, 2, 5, 11, 16, 19…
## $ GW16_Points    &lt;int&gt; 32, 24, 46, 19, 18, 23, 22, 16, 22, 22, 17, 38, 24, 22…
## $ GW16_Standing  &lt;int&gt; 3, 5, 1, 12, 13, 7, 9, 15, 8, 10, 14, 2, 6, 11, 17, 19…
## $ GW17_Points    &lt;int&gt; 35, 25, 49, 20, 21, 26, 22, 19, 25, 23, 18, 39, 24, 22…
## $ GW17_Standing  &lt;int&gt; 3, 6, 1, 13, 12, 5, 10, 14, 7, 9, 16, 2, 8, 11, 17, 19…
## $ GW18_Points    &lt;int&gt; 38, 25, 49, 20, 24, 26, 23, 19, 28, 23, 19, 39, 27, 25…
## $ GW18_Standing  &lt;int&gt; 3, 8, 1, 13, 10, 7, 11, 14, 5, 12, 15, 2, 6, 9, 18, 19…
## $ GW19_Points    &lt;int&gt; 38, 28, 52, 20, 24, 29, 24, 20, 29, 26, 22, 39, 30, 25…
## $ GW19_Standing  &lt;int&gt; 3, 8, 1, 15, 12, 6, 11, 16, 7, 9, 13, 2, 5, 10, 18, 20…
## $ GW20_Points    &lt;int&gt; 41, 31, 55, 23, 24, 30, 24, 20, 29, 27, 25, 42, 30, 25…
## $ GW20_Standing  &lt;int&gt; 3, 5, 1, 14, 13, 6, 12, 16, 8, 9, 10, 2, 7, 11, 18, 20…
## $ GW21_Points    &lt;int&gt; 44, 31, 58, 24, 24, 30, 27, 20, 29, 28, 25, 45, 30, 25…
## $ GW21_Standing  &lt;int&gt; 3, 5, 1, 14, 15, 6, 10, 18, 8, 9, 11, 2, 7, 13, 17, 20…
## $ GW22_Points    &lt;int&gt; 47, 34, 61, 24, 24, 30, 28, 20, 32, 29, 28, 45, 31, 26…
## $ GW22_Standing  &lt;int&gt; 2, 5, 1, 14, 15, 8, 10, 19, 6, 9, 11, 3, 7, 13, 18, 20…
## $ GW23_Points    &lt;int&gt; 48, 34, 64, 25, 27, 31, 29, 20, 33, 30, 29, 45, 34, 29…
## $ GW23_Standing  &lt;int&gt; 2, 5, 1, 15, 14, 8, 10, 19, 7, 9, 11, 3, 6, 12, 18, 20…
## $ GW24_Points    &lt;int&gt; 51, 34, 70, 25, 30, 34, 30, 23, 33, 30, 30, 48, 34, 30…
## $ GW24_Standing  &lt;int&gt; 2, 5, 1, 15, 13, 6, 10, 18, 8, 11, 12, 3, 7, 14, 16, 2…
## $ GW25_Points    &lt;int&gt; 51, 35, 73, 26, 31, 37, 31, 26, 36, 30, 33, 49, 35, 31…
## $ GW25_Standing  &lt;int&gt; 2, 7, 1, 15, 11, 5, 10, 16, 6, 14, 9, 3, 8, 12, 17, 20…
## $ GW26_Points    &lt;int&gt; 54, 38, 76, 27, 34, 40, 34, 26, 39, 30, 36, 50, 36, 31…
## $ GW26_Standing  &lt;int&gt; 2, 7, 1, 15, 11, 5, 10, 16, 6, 14, 9, 3, 8, 13, 17, 20…
## $ GW27_Points    &lt;int&gt; 57, 41, 79, 28, 37, 40, 37, 26, 40, 33, 36, 50, 39, 31…
## $ GW27_Standing  &lt;int&gt; 2, 5, 1, 15, 10, 6, 9, 16, 7, 13, 11, 3, 8, 14, 17, 20…
## $ GW28_Points    &lt;int&gt; 57, 42, 79, 28, 38, 40, 37, 27, 40, 36, 37, 50, 42, 32…
## $ GW28_Standing  &lt;int&gt; 2, 5, 1, 15, 9, 7, 10, 18, 8, 12, 11, 3, 6, 14, 19, 20…
## $ GW29_Points    &lt;int&gt; 57, 45, 82, 29, 39, 41, 40, 27, 43, 39, 37, 53, 43, 35…
## $ GW29_Standing  &lt;int&gt; 2, 5, 1, 15, 10, 8, 9, 18, 7, 11, 12, 3, 6, 13, 19, 20…
## $ GW30_Points    &lt;int&gt; 63, 46, 83, 32, 39, 42, 40, 27, 44, 42, 38, 54, 46, 38…
## $ GW30_Standing  &lt;int&gt; 2, 5, 1, 15, 11, 8, 10, 18, 7, 9, 12, 3, 6, 13, 19, 20…
## $ GW31_Points    &lt;int&gt; 63, 49, 86, 33, 42, 45, 43, 27, 44, 42, 41, 55, 49, 39…
## $ GW31_Standing  &lt;int&gt; 2, 5, 1, 15, 11, 7, 9, 18, 8, 10, 12, 3, 6, 13, 19, 20…
## $ GW32_Points    &lt;int&gt; 66, 52, 86, 33, 45, 45, 46, 27, 47, 42, 44, 55, 52, 42…
## $ GW32_Standing  &lt;int&gt; 2, 5, 1, 15, 10, 9, 8, 19, 7, 12, 11, 3, 6, 13, 18, 20…
## $ GW33Points     &lt;int&gt; 66, 55, 89, 33, 46, 48, 49, 27, 48, 42, 44, 58, 52, 43…
## $ GW33_Standing  &lt;int&gt; 2, 5, 1, 15, 10, 8, 7, 19, 9, 14, 11, 3, 6, 12, 18, 20…
## $ GW34_Points    &lt;int&gt; 69, 58, 92, 36, 49, 49, 50, 28, 51, 42, 45, 59, 52, 43…
## $ GW34_Standing  &lt;int&gt; 2, 5, 1, 15, 10, 9, 8, 18, 7, 14, 11, 4, 6, 13, 19, 20…
## $ GW35_Points    &lt;int&gt; 72, 59, 93, 36, 50, 52, 50, 31, 54, 42, 45, 59, 55, 43…
## $ GW35_Standing  &lt;int&gt; 2, 5, 1, 15, 10, 8, 9, 18, 7, 14, 11, 4, 6, 13, 19, 20…
## $ GW36_Points    &lt;int&gt; 75, 62, 93, 37, 51, 55, 53, 31, 54, 42, 46, 62, 56, 43…
## $ GW36_Standing  &lt;int&gt; 2, 5, 1, 16, 10, 7, 9, 18, 8, 14, 11, 4, 6, 13, 19, 20…
## $ GW37_Points    &lt;int&gt; 78, 63, 96, 38, 54, 58, 53, 31, 54, 42, 49, 62, 59, 44…
## $ GW37_Standing  &lt;int&gt; 2, 3, 1, 16, 9, 7, 10, 19, 8, 14, 11, 5, 6, 13, 17, 20…
## $ GW38_Points    &lt;int&gt; 81, 66, 99, 41, 54, 59, 56, 34, 54, 43, 49, 62, 59, 44…
## $ GW38_Standing  &lt;int&gt; 2, 3, 1, 15, 10, 6, 8, 18, 9, 14, 12, 5, 7, 13, 17, 20…</code></pre>
<pre><code>## Observations: 522
## Variables: 41
## $ id                        &lt;int&gt; 816, 622, 812, 287, 158, 576, 506, 491, 988…
## $ name                      &lt;fct&gt; Kevin De Bruyne, Bruno Fernandes, Ricardo P…
## $ nationality               &lt;fct&gt; be, pt, pt, es, dz, sn, eg, gb-eng, gb-eng,…
## $ team                      &lt;fct&gt; Man City, Man Utd, Leicester, Wolves, Man C…
## $ team_id                   &lt;int&gt; 875, 314, 652, 518, 875, 339, 339, 875, 314…
## $ age                       &lt;int&gt; 29, 26, 26, 24, 29, 28, 28, 25, 22, 23, 27,…
## $ height                    &lt;int&gt; 181, 179, 175, 178, 179, 175, 175, 170, 180…
## $ weight                    &lt;int&gt; 68, 69, 70, 72, 67, 69, 71, 69, 70, 73, 86,…
## $ position                  &lt;fct&gt; Midfielder, Midfielder, Defender, Forward, …
## $ roles                     &lt;fct&gt; &quot;M_C,M_L,M_R,FW&quot;, &quot;M_C,M_L,M_R&quot;, &quot;D_L,D_R,M…
## $ games                     &lt;int&gt; 35, 14, 28, 37, 33, 35, 34, 33, 31, 31, 29,…
## $ exit_on_sub               &lt;int&gt; 3, 0, 0, 10, 12, 4, 1, 3, 0, 2, 0, 0, 1, 7,…
## $ minutes                   &lt;int&gt; 2800, 1223, 2520, 2608, 1942, 2756, 2888, 2…
## $ rating_m                  &lt;dbl&gt; 7.97, 7.73, 7.50, 7.49, 7.48, 7.45, 7.40, 7…
## $ goals                     &lt;int&gt; 13, 8, 3, 4, 11, 18, 19, 20, 17, 6, 18, 5, …
## $ assists                   &lt;int&gt; 20, 7, 2, 9, 9, 7, 10, 1, 7, 3, 2, 1, 6, 7,…
## $ yel_cards                 &lt;int&gt; 3, 2, 1, 1, 0, 3, 1, 5, 3, 4, 4, 1, 1, 4, 4…
## $ red_cards                 &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ shots_m                   &lt;dbl&gt; 2.8, 3.1, 0.6, 1.2, 2.2, 2.2, 3.9, 3.0, 3.1…
## $ aerials_won_m             &lt;dbl&gt; 0.5, 0.2, 1.5, 1.2, 0.3, 1.2, 0.4, 0.7, 0.7…
## $ motm                      &lt;int&gt; 10, 3, 2, 6, 3, 7, 6, 1, 7, 4, 4, 5, 4, 4, …
## $ successful_passes_pt      &lt;dbl&gt; 81.5, 75.7, 78.9, 74.4, 90.1, 81.6, 76.5, 8…
## $ key_passes_m              &lt;dbl&gt; 3.9, 2.1, 1.0, 1.3, 1.8, 1.7, 1.8, 1.5, 1.1…
## $ dribbles_won_m            &lt;dbl&gt; 1.4, 1.1, 2.1, 5.0, 1.6, 2.0, 1.5, 1.7, 1.9…
## $ fouls_given_m             &lt;dbl&gt; 0.8, 1.0, 1.3, 2.1, 0.9, 1.5, 0.5, 1.2, 1.5…
## $ offside_m                 &lt;dbl&gt; 0.1, 0.1, 0.0, 0.2, 0.4, 0.4, 0.6, 0.4, 0.4…
## $ dispossessed_m            &lt;dbl&gt; 0.9, 0.9, 1.1, 1.8, 1.0, 1.6, 2.0, 1.8, 1.1…
## $ passes_m                  &lt;dbl&gt; 54.5, 55.5, 56.1, 19.2, 33.2, 31.5, 28.8, 3…
## $ accurate_crosses_m        &lt;dbl&gt; 2.1, 1.0, 0.3, 1.2, 0.6, 0.3, 0.3, 0.2, 0.3…
## $ accurate_long_passes_m    &lt;dbl&gt; 3.5, 3.3, 2.1, 0.2, 1.7, 1.0, 0.4, 0.3, 1.2…
## $ accurate_through_passes_m &lt;dbl&gt; 0.4, 0.3, 0.1, 0.1, 0.2, 0.1, 0.1, 0.1, 0.2…
## $ tackles_m                 &lt;dbl&gt; 1.3, 1.6, 4.2, 0.9, 0.8, 1.3, 0.5, 0.8, 0.4…
## $ interceptions_m           &lt;dbl&gt; 0.5, 0.8, 1.8, 0.4, 0.5, 0.4, 0.2, 0.5, 0.3…
## $ fouls_m                   &lt;dbl&gt; 0.7, 0.6, 1.6, 1.1, 0.4, 1.3, 0.5, 0.9, 0.7…
## $ clearances_m              &lt;dbl&gt; 0.7, 1.0, 2.6, 0.4, 0.2, 0.2, 0.1, 0.1, 0.5…
## $ dribbled_past_m           &lt;dbl&gt; 1.4, 2.4, 1.9, 0.4, 0.8, 0.8, 0.5, 0.7, 0.5…
## $ owm_goals                 &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ gk_in_goal_area_saves_m   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ gk_inside_box_saves_m     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ gk_outside_box_saves_m    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ gk_saves_m                &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…</code></pre>
<pre><code>## Observations: 22,502
## Variables: 35
## $ X                 &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, …
## $ assists           &lt;int&gt; 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ bonus             &lt;int&gt; 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ bps               &lt;int&gt; 1, 1, 1, 2, 53, 3, 22, 2, -5, 0, -1, 4, 0, 0, -1, 1…
## $ clean_sheets      &lt;int&gt; 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ creativity        &lt;dbl&gt; 0.1, 0.3, 4.8, 0.6, 23.8, 10.6, 0.3, 5.8, 1.3, 0.0,…
## $ element           &lt;int&gt; 534, 534, 534, 534, 534, 534, 534, 534, 534, 534, 5…
## $ fixture           &lt;int&gt; 37, 43, 58, 63, 72, 81, 92, 104, 115, 124, 134, 141…
## $ goals_conceded    &lt;int&gt; 1, 1, 0, 1, 0, 1, 2, 0, 2, 0, 2, 1, 0, 0, 0, 1, 0, …
## $ goals_scored      &lt;int&gt; 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ ict_index         &lt;dbl&gt; 0.0, 2.2, 2.5, 0.1, 20.1, 3.6, 0.2, 4.8, 0.3, 0.0, …
## $ influence         &lt;dbl&gt; 0.2, 1.0, 2.0, 0.2, 70.2, 4.4, 0.0, 0.0, 0.0, 0.0, …
## $ kickoff_time      &lt;fct&gt; 2019-08-31 14:00:00, 2019-09-14 14:00:00, 2019-09-2…
## $ minutes           &lt;int&gt; 24, 6, 20, 25, 79, 45, 79, 85, 45, 0, 75, 75, 0, 0,…
## $ opponent_team     &lt;fct&gt; Man City, Burnley, Newcastle United, Chelsea, Totte…
## $ own_goals         &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ penalties_missed  &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ penalties_saved   &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ red_cards         &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ round             &lt;int&gt; 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1…
## $ saves             &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ selected          &lt;int&gt; 0, 14029, 22804, 32699, 35026, 110944, 146247, 2632…
## $ team_a_score      &lt;int&gt; 0, 1, 0, 0, 0, 1, 2, 0, 1, 2, 1, 2, 2, 1, 1, 1, 0, …
## $ team_h_score      &lt;int&gt; 4, 1, 0, 2, 3, 2, 3, 2, 3, 0, 2, 1, 2, 1, 0, 2, 2, …
## $ threat            &lt;int&gt; 0, 21, 18, 0, 107, 21, 2, 46, 4, 0, 17, 27, 0, 0, 2…
## $ total_points      &lt;int&gt; 1, 1, 1, 1, 13, 1, 8, 2, 1, 0, 2, 2, 0, 0, 1, 2, 0,…
## $ transfers_balance &lt;int&gt; 0, 10589, 8090, 8437, 2156, 70802, 34969, 109148, -…
## $ transfers_in      &lt;int&gt; 0, 13500, 11749, 13439, 5952, 81069, 42593, 118970,…
## $ transfers_out     &lt;int&gt; 0, 2911, 3659, 5002, 3796, 10267, 7624, 9822, 29857…
## $ value             &lt;dbl&gt; 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.6, 4.6, 4.7, 4.7, 4…
## $ was_home          &lt;fct&gt; False, True, False, False, True, False, True, True,…
## $ yellow_cards      &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ full              &lt;fct&gt; Aaron Connolly, Aaron Connolly, Aaron Connolly, Aar…
## $ team              &lt;fct&gt; Brighton, Brighton, Brighton, Brighton, Brighton, B…
## $ ppm               &lt;dbl&gt; 0.2222222, 0.2222222, 0.2222222, 0.2222222, 2.88888…</code></pre>
<p>For this project, I am examining the English Premier League statistics by players stats, like height/age compared to their respective position. For example, in the datasets “epl_players_stats.csv” and “players_1920_fin.csv” from FiveThirtyEight, the file goes into full detail about players like height, position, goals per game, goals given up, age, ect, so I will be examining if a player if more likely to succeed in this league based on their height or age. The “players_1920_fin.csv”" there were 22,502 observations and 35 Variables, and “epl_players_stats.csv” has 522 observations and 41 variables. The variable codes is a factor with multiple levels explaing what teams each player plays for and their statistics for the 19/20 season.</p>
<p>The other two datasets “EPL_19_20_GW_Timeseries.csv” and “epl2020.csv” go into detail for the 19/20 statitics for each team in the English Premier League. In these data sets, we can find the results week by week of each team in the EPL and variable like win’s, loss’s, ties, points gained, goals given up, goals scored, ect.. The “EPL_19_20_GW_Timeseries.csv” has 1,048,575 observations and 77 variable and the “epl2020.csv” data set consits of 576 observations and 45 variables. These files have many levels going into full detail week by week, so i will have many outcomes to analyze.</p>
<p>*Question 1: First, do soccer players score more goals based on their height? I will analyze each players statistics for the 19/20 season based off their heights. Go into detail about if tall players score more goals than short players or vise versa. The measurement will be based off the overall median height of every player in the league. To test this, I will be putting the data organized in a data visualization like a scatter plot.</p>
<p>*Question 2: Second, do teams tend to preform better with older, experienced players or young, talented players. Getting the average age of the players for each team and basing that with their results. Respectively, comparing if they score more goals, prevent more goals, and their wins, then plotting this into a bar chart.</p>
<p>*Question 3: Third, overall, do teams that spend more money correlate to their performance. Do team that spend more money obtaining and paying more players translate to more wins. I will be comparing the total amount spent by each team and comparing them in a bar chart.</p>
<p>*Question 4: Fourth, To be announced.</p>
<pre><code>## Observations: 22,800
## Variables: 10
## $ person      &lt;fct&gt; &quot;Constable Darius Quimby&quot;, &quot;Sheriff Cornelius Hogeboom&quot;, …
## $ dept        &lt;fct&gt; &quot;Albany County Constable&#39;s Office, NY&quot;, &quot;Columbia County …
## $ eow         &lt;fct&gt; &quot;EOW: Monday, January 3, 1791&quot;, &quot;EOW: Saturday, October 2…
## $ cause       &lt;fct&gt; Cause of Death: Gunfire, Cause of Death: Gunfire, Cause o…
## $ cause_short &lt;fct&gt; Gunfire, Gunfire, Gunfire, Gunfire, Gunfire, Gunfire, Sta…
## $ date        &lt;fct&gt; 1791-01-03, 1791-10-22, 1792-05-17, 1794-01-11, 1797-11-1…
## $ year        &lt;int&gt; 1791, 1791, 1792, 1794, 1797, 1804, 1806, 1807, 1808, 180…
## $ canine      &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, F…
## $ dept_name   &lt;fct&gt; Albany County Constable&#39;s Office, Columbia County Sheriff…
## $ state       &lt;fct&gt;  NY,  NY,  NY,  US,  SC,  NC,  NY,  KY,  ME,  MD,  US,  U…</code></pre>
<pre><code>## Observations: 467
## Variables: 34
## $ name                 &lt;fct&gt; A&#39;donte Washington, Aaron Rutledge, Aaron Siler,…
## $ age                  &lt;fct&gt; 16, 27, 26, 25, 29, 29, 22, 35, 44, 31, 76, 40, …
## $ gender               &lt;fct&gt; Male, Male, Male, Male, Male, Male, Male, Male, …
## $ raceethnicity        &lt;fct&gt; Black, White, White, Hispanic/Latino, White, Whi…
## $ month                &lt;fct&gt; February, April, March, March, March, March, Mar…
## $ day                  &lt;int&gt; 23, 2, 14, 11, 19, 7, 27, 26, 28, 7, 26, 12, 20,…
## $ year                 &lt;int&gt; 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, …
## $ streetaddress        &lt;fct&gt; Clearview Ln, 300 block Iris Park Dr, 22nd Ave a…
## $ city                 &lt;fct&gt; Millbrook, Pineville, Kenosha, South Gate, Munro…
## $ state                &lt;fct&gt; AL, LA, WI, CA, OH, AZ, CA, CA, TX, MI, CA, CA, …
## $ latitude             &lt;dbl&gt; 32.52958, 31.32174, 42.58356, 33.93930, 41.14857…
## $ longitude            &lt;dbl&gt; -86.36283, -92.43486, -87.83571, -118.21946, -81…
## $ state_fp             &lt;int&gt; 1, 22, 55, 6, 39, 4, 6, 6, 48, 26, 6, 6, 48, 18,…
## $ county_fp            &lt;int&gt; 51, 79, 59, 37, 153, 13, 29, 37, 41, 81, 31, 59,…
## $ tract_ce             &lt;int&gt; 30902, 11700, 1200, 535607, 530800, 111602, 700,…
## $ geo_id               &lt;dbl&gt; 1051030902, 22079011700, 55059001200, 6037535607…
## $ county_id            &lt;int&gt; 1051, 22079, 55059, 6037, 39153, 4013, 6029, 603…
## $ namelsad             &lt;fct&gt; Census Tract 309.02, Census Tract 117, Census Tr…
## $ lawenforcementagency &lt;fct&gt; Millbrook Police Department, Rapides Parish Sher…
## $ cause                &lt;fct&gt; Gunshot, Gunshot, Gunshot, Gunshot, Gunshot, Gun…
## $ armed                &lt;fct&gt; No, No, No, Firearm, No, No, Firearm, Non-lethal…
## $ pop                  &lt;int&gt; 3779, 2769, 4079, 4343, 6809, 4682, 5027, 5238, …
## $ share_white          &lt;fct&gt; 60.5, 53.8, 73.8, 1.2, 92.5, 7, 50.8, 8.6, 14.6,…
## $ share_black          &lt;fct&gt; 30.5, 36.2, 7.7, 0.6, 1.4, 7.7, 0.3, 0.2, 17.7, …
## $ share_hispanic       &lt;fct&gt; 5.6, 0.5, 16.8, 98.8, 1.7, 79, 44.2, 84.1, 66.3,…
## $ p_income             &lt;fct&gt; 28375, 14678, 25286, 17194, 33954, 15523, 25949,…
## $ h_income             &lt;int&gt; 51367, 27972, 45365, 48295, 68785, 20833, 58068,…
## $ county_income        &lt;int&gt; 54766, 40930, 54930, 55909, 49669, 53596, 48552,…
## $ comp_income          &lt;dbl&gt; 0.9379359, 0.6834107, 0.8258693, 0.8638144, 1.38…
## $ county_bucket        &lt;int&gt; 3, 2, 2, 3, 5, 1, 4, 4, 2, 3, 4, 5, 3, 4, 3, 1, …
## $ nat_bucket           &lt;int&gt; 3, 1, 3, 3, 4, 1, 4, 4, 1, 2, 3, 5, 3, 2, 2, 1, …
## $ pov                  &lt;fct&gt; 14.1, 28.8, 14.6, 11.7, 1.9, 58, 17.2, 12.2, 37.…
## $ urate                &lt;dbl&gt; 0.09768638, 0.06572379, 0.16629314, 0.12482727, …
## $ college              &lt;dbl&gt; 0.16850951, 0.11140236, 0.14731227, 0.05013293, …</code></pre>
<pre><code>## Observations: 75
## Variables: 8
## $ city              &lt;fct&gt; &quot;New York&quot;, &quot;Chicago&quot;, &quot;Los Angeles&quot;, &quot;Washington&quot;,…
## $ police_force_size &lt;int&gt; 32300, 12120, 10100, 9340, 7700, 6045, 4475, 4460, …
## $ all               &lt;dbl&gt; 0.6179567, 0.8750000, 0.2282178, 0.1156317, 0.29220…
## $ white             &lt;dbl&gt; 0.44638656, 0.87196262, 0.15277778, 0.05677419, 0.1…
## $ non.white         &lt;dbl&gt; 0.7644189, 0.8774003, 0.2638484, 0.1573651, 0.39925…
## $ black             &lt;fct&gt; 0.770891365, 0.89740566, 0.387387387, 0.170189099, …
## $ hispanic          &lt;fct&gt; 0.762860728, 0.83982684, 0.217679558, 0.08988764, 0…
## $ asian             &lt;fct&gt; 0.749235474, 0.966666667, 0.305263158, 0.230769231,…</code></pre>
<p>Using data obtained from FiveThirtyEight from multiple sources and the census, the next dataset I am going to investigate is the data of police killings and deaths in the United States through 2015-2016. The variables in the files include the date, name of state, name of deceased, race, and gender. The US population data is from the US Census Bureau website. There are 22,800 observations and 10 variables in the “clean_data.csv” file, which go into depth about police deaths. The “police_killings.csv” goes into depth about the police killing, which has 467 observations, and 34 variables. On the last dataset, the data is a collected from multiple police station from the biggest cities in the United States. With all the different data available, there should be enough data for me to analyze.</p>
<p>*Question 1: First, where do the police killings tend to happen more frequently. Using the “police_killings.csv” data I will analyze where these police killings tend to happen more frequently, like is there a state with notably more killings than the rest. I will preform this analysis with grouping, filtering, and creating a spacial map with ggplot to visualize my analysis.</p>
<p>*Question 2: Second, do a certain race tend to be killed more? Again, using the “police_killings.csv” data, I will group the police killings by race and compare the number of killings by race. Also, I will being doing this for both police killing and police deaths, and I will be visualizing my findings with a bar chart for easy comparison.</p>
<p>*Question 3: Third, Does the size of the task force correspond with the number of police killings? Using the third data set of “police-locals.csv”, I will analyze if with more police officers tend to be more police killings. I will create a new variable, setting the new variable with the task force size divided by the amount of police killings and compare that to different cities. This can be answered using a simple bar graph to visualize my analysis.</p>
<p>*Question 4: Fourth, to be decided.</p>
